### PR TITLE
@RequestParam and named parameters model support.

### PR DESCRIPTION
**Pull request by bmustiata**

### CODE REVIEW

**Comment by mkowalzik** [comment]
Nice, so far, but it is lacking some tests and modifications of the service template. So I conclude it is work in progress, isn't it?
Hint: It's moving towards Angular HttpClient so there is a new template in #56 - would be great if you could rebase your changes on top of c8739e558a8cd0b29f123af1aa6a128a0a280a45.

**Comment by bmustiata** [comment]
I will rebase.

The problem is I'm not using Angular, so I need to rewrite the templates.
Unfortunately as well is that some paths are hardcoded, and I can't just
change the templates with other templates. I ended up overwriting the
resources directly. I can't test the Angular templates if they work, this
is why the "model changes" in the PR title :). I intend to write my own
templates, but I can't since the data is not available in the model.

It would be nice to globally reconfigure all the template paths (maybe
another annotation?)

**Comment by mkowalzik** [comment]
Tanks and yes, a global configuration of all template paths would be a nice feature. I already had thought of this and there are already issues #5 or #41, but they had no priority because we only use Angular.
I think a new config annotation would probably the best solution. Would you like to help implement it?
In the meantime,  I will merge your pull request, add some tests and extend the angular service template to incorporate the @RequestParams, so it can be released this weekend.

**Comment by bmustiata** [comment]
I'm taking a stab at it.

**Pull request merged**
